/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package laboratorio07;




/**
 *
 * @author Leonardo
 */
public class JFrameNuevaCita extends javax.swing.JFrame {
      private   JFrameCitaPrincipal padre;
      private Cita cita;
      
      private boolean edit = false;
      
      private Medico medicoSelect;
      private Paciente pacienteSelect;
      private Especialidad especialidadSelect;


    /**
     * Creates new form JFrameNuevaCita
     */
    public JFrameNuevaCita(JFrameCitaPrincipal padre) {
        initComponents();
        this.padre = padre;
        
        ComEspecialidad.removeAllItems();
        ComEspecialidad.setEnabled(false);
        
        ComHora.removeAllItems();
        for(String hora: GestorCitas.horas){
                    ComHora.addItem(hora);
        }
        
        
          ComFecha.removeAllItems();
          for(String fecha: GestorCitas.fechas){
                    ComFecha.addItem(fecha);
        }

    }
    
    
    
    
    
     public JFrameNuevaCita(JFrameCitaPrincipal padre, Cita cita) {
        initComponents();
        this.padre = padre;
        this.cita = cita;
        this.edit = true;
       this.btnBuscarPaciente.setVisible(false);
       this.btnBuscarMedico.setVisible(false);
       this.btnCrearCita.setVisible(false);
       lblNuevaCita.setText("Visualizar Cita");
       
       this.txtMedico.setText(cita.getMedico().getTexto());
       this.txtPaciente.setText(cita.getPaciente().getTexto());
       
       ComEspecialidad.removeAllItems();
       ComEspecialidad.addItem(cita.getEspecialidad().getNombre());
       
       ComFecha.removeAllItems();
       ComFecha.addItem(GestorCitas.fechas.get(cita.getFecha()));
       
       ComHora.removeAllItems();
       ComHora.addItem(GestorCitas.horas.get(cita.getHora()));
    }

    


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblNuevaCita = new javax.swing.JLabel();
        txtPaciente = new javax.swing.JTextField();
        txtMedico = new javax.swing.JTextField();
        ComFecha = new javax.swing.JComboBox<>();
        ComHora = new javax.swing.JComboBox<>();
        btnBuscarPaciente = new javax.swing.JButton();
        btnBuscarMedico = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnCrearCita = new javax.swing.JButton();
        ComEspecialidad = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));

        lblNuevaCita.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        lblNuevaCita.setForeground(new java.awt.Color(0, 0, 0));
        lblNuevaCita.setText("NUEVA CITA");

        txtPaciente.setBackground(new java.awt.Color(255, 255, 255));
        txtPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPacienteActionPerformed(evt);
            }
        });

        txtMedico.setBackground(new java.awt.Color(255, 255, 255));

        ComFecha.setBackground(new java.awt.Color(255, 255, 255));

        ComHora.setBackground(new java.awt.Color(255, 255, 255));

        btnBuscarPaciente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/laboratorio07/Group 6.png"))); // NOI18N
        btnBuscarPaciente.setBorder(null);
        btnBuscarPaciente.setContentAreaFilled(false);
        btnBuscarPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarPacienteActionPerformed(evt);
            }
        });

        btnBuscarMedico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/laboratorio07/Group 7.png"))); // NOI18N
        btnBuscarMedico.setBorder(null);
        btnBuscarMedico.setContentAreaFilled(false);
        btnBuscarMedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarMedicoActionPerformed(evt);
            }
        });

        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/laboratorio07/Group 9 (1).png"))); // NOI18N
        btnCancelar.setBorder(null);
        btnCancelar.setContentAreaFilled(false);
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnCrearCita.setIcon(new javax.swing.ImageIcon(getClass().getResource("/laboratorio07/Group 8.png"))); // NOI18N
        btnCrearCita.setBorder(null);
        btnCrearCita.setContentAreaFilled(false);
        btnCrearCita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearCitaActionPerformed(evt);
            }
        });

        ComEspecialidad.setBackground(new java.awt.Color(255, 255, 255));
        ComEspecialidad.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                ComEspecialidadPropertyChange(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNuevaCita)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(ComEspecialidad, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtMedico, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtPaciente, javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(ComFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(28, 28, 28)
                                    .addComponent(btnCancelar)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                            .addComponent(ComHora, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCrearCita)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btnBuscarMedico)
                        .addComponent(btnBuscarPaciente)))
                .addGap(22, 22, 22))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(lblNuevaCita)
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtMedico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnBuscarMedico)))
                    .addComponent(btnBuscarPaciente))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(ComEspecialidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ComFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ComHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                        .addComponent(btnCancelar))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnCrearCita)))
                .addGap(29, 29, 29))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //ENCAPSULAR
    //---------------------------------------------------------------------------------------
    public void setPaciente(Paciente paciente){
        this.pacienteSelect = paciente;
        
        txtPaciente.setText(paciente.getTexto());
    }
    
    public void setMedico(Medico medico){
        this.medicoSelect = medico;
        txtMedico.setText(this.medicoSelect.getTexto());
        
        
        
        
        ComEspecialidad.removeAllItems();
        for(Especialidad espec: medico.getEspecialidades()){
            ComEspecialidad.addItem(espec.getNombre());
        }
        
        
        ComEspecialidad.setEnabled(true);
        
    }
    

    //-----------------------------------------------------------------------------------------
    private void btnBuscarPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarPacienteActionPerformed

        JFrameListarPacientes pantallaListarPacientes = new JFrameListarPacientes(this);
        pantallaListarPacientes.setLocationRelativeTo(this);
        pantallaListarPacientes.setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_btnBuscarPacienteActionPerformed

    private void btnBuscarMedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarMedicoActionPerformed

        JFrameListarMedicos pantallaListarMedicos = new JFrameListarMedicos(this);
        pantallaListarMedicos.setLocationRelativeTo(this);
        pantallaListarMedicos.setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_btnBuscarMedicoActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed

        Salir();
 
        
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void txtPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPacienteActionPerformed

    }//GEN-LAST:event_txtPacienteActionPerformed

    public void guardarCita(){
       
        
        if(medicoSelect != null && pacienteSelect != null){
             especialidadSelect = medicoSelect.getEspecialidades().get(ComEspecialidad.getSelectedIndex());
             
             cita = new Cita(medicoSelect, pacienteSelect,especialidadSelect);
             cita.setFecha(ComFecha.getSelectedIndex());
             cita.setHora(ComHora.getSelectedIndex());
             this.padre.AgregarCita(cita);
             
             
             //Si existe un medico y un paciente
             //entonces
             //voy a obtener la especialidadd selecionada
             //y luego agrego la cita
        }
            
        

    }
    
    
    private void btnCrearCitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearCitaActionPerformed

        guardarCita();
        Salir();
    }//GEN-LAST:event_btnCrearCitaActionPerformed

    private void ComEspecialidadPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_ComEspecialidadPropertyChange
        // TODO add your handling code here:
        if(this.medicoSelect != null){
        Especialidad espec = this.medicoSelect.getEspecialidades().get(ComEspecialidad.getSelectedIndex());
        especialidadSelect = espec;
        }
        
    }//GEN-LAST:event_ComEspecialidadPropertyChange

    
    
    
    // SALIR Y GUARDAR
    
    private void Salir(){
        padre.setVisible(true);
        this.dispose();
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameNuevaCita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameNuevaCita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameNuevaCita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameNuevaCita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameNuevaCita(new JFrameCitaPrincipal()).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComEspecialidad;
    private javax.swing.JComboBox<String> ComFecha;
    private javax.swing.JComboBox<String> ComHora;
    private javax.swing.JButton btnBuscarMedico;
    private javax.swing.JButton btnBuscarPaciente;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnCrearCita;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblNuevaCita;
    private javax.swing.JTextField txtMedico;
    private javax.swing.JTextField txtPaciente;
    // End of variables declaration//GEN-END:variables
}
